server:
  port: 8082
  error:
    include-stacktrace: always
    whitelabel:
      enabled: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update

# /actuator ¼à¿Ø¶Ëµã
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



logging:
  level:
    org.springframework.test: info
